apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        io.kompose.service: web
    name: web
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: web
    strategy: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                io.kompose.service: web
        spec:
            containers:
                - image: tuna/docker-counter23
                  name: web
                  ports:
                    - containerPort: 5000
                  resources: {}
            restartPolicy: Always
status: {}
